#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall -fexceptions -std=c++17
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC) -Iinclude
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/sfxobjdump

INC_RELEASE = $(INC) -Iinclude
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/sfxobjdump

OBJ_DEBUG = $(OBJDIR_DEBUG)/main.o $(OBJDIR_DEBUG)/src/BSPTree.o $(OBJDIR_DEBUG)/src/BufferReader.o $(OBJDIR_DEBUG)/src/Face.o $(OBJDIR_DEBUG)/src/Normal.o $(OBJDIR_DEBUG)/src/SFXObject.o $(OBJDIR_DEBUG)/src/Triangle.o $(OBJDIR_DEBUG)/src/Vertex.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/src/BSPTree.o $(OBJDIR_RELEASE)/src/BufferReader.o $(OBJDIR_RELEASE)/src/Face.o $(OBJDIR_RELEASE)/src/Normal.o $(OBJDIR_RELEASE)/src/SFXObject.o $(OBJDIR_RELEASE)/src/Triangle.o $(OBJDIR_RELEASE)/src/Vertex.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cpp -o $(OBJDIR_DEBUG)/main.o

$(OBJDIR_DEBUG)/src/BSPTree.o: src/BSPTree.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/BSPTree.cpp -o $(OBJDIR_DEBUG)/src/BSPTree.o

$(OBJDIR_DEBUG)/src/BufferReader.o: src/BufferReader.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/BufferReader.cpp -o $(OBJDIR_DEBUG)/src/BufferReader.o

$(OBJDIR_DEBUG)/src/Face.o: src/Face.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Face.cpp -o $(OBJDIR_DEBUG)/src/Face.o

$(OBJDIR_DEBUG)/src/Normal.o: src/Normal.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Normal.cpp -o $(OBJDIR_DEBUG)/src/Normal.o

$(OBJDIR_DEBUG)/src/SFXObject.o: src/SFXObject.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/SFXObject.cpp -o $(OBJDIR_DEBUG)/src/SFXObject.o

$(OBJDIR_DEBUG)/src/Triangle.o: src/Triangle.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Triangle.cpp -o $(OBJDIR_DEBUG)/src/Triangle.o

$(OBJDIR_DEBUG)/src/Vertex.o: src/Vertex.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Vertex.cpp -o $(OBJDIR_DEBUG)/src/Vertex.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)
	rm -rf $(OBJDIR_DEBUG)/src

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/src/BSPTree.o: src/BSPTree.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/BSPTree.cpp -o $(OBJDIR_RELEASE)/src/BSPTree.o

$(OBJDIR_RELEASE)/src/BufferReader.o: src/BufferReader.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/BufferReader.cpp -o $(OBJDIR_RELEASE)/src/BufferReader.o

$(OBJDIR_RELEASE)/src/Face.o: src/Face.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Face.cpp -o $(OBJDIR_RELEASE)/src/Face.o

$(OBJDIR_RELEASE)/src/Normal.o: src/Normal.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Normal.cpp -o $(OBJDIR_RELEASE)/src/Normal.o

$(OBJDIR_RELEASE)/src/SFXObject.o: src/SFXObject.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/SFXObject.cpp -o $(OBJDIR_RELEASE)/src/SFXObject.o

$(OBJDIR_RELEASE)/src/Triangle.o: src/Triangle.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Triangle.cpp -o $(OBJDIR_RELEASE)/src/Triangle.o

$(OBJDIR_RELEASE)/src/Vertex.o: src/Vertex.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Vertex.cpp -o $(OBJDIR_RELEASE)/src/Vertex.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)
	rm -rf $(OBJDIR_RELEASE)/src

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

